version: "3.9"
services:

# Postgres database
  postgres:
    image: "postgres:16.1-bookworm"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keycloak

# Keycloak
  keycloak:
    image: "quay.io/keycloak/keycloak:22.0.5"
    ports:
      - "8080:8080"
    environment:
      - KC_HEALTH_ENABLED=true

      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_PASSWORD=postgres
      - KC_DB_SCHEMA=public
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=postgres
      - KC_METRICS_ENABLED=true

      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

    command: 
    - "start-dev --import-realm"

    volumes:
    - ./realms:/opt/keycloak/data/import

    depends_on:
      - postgres
  
# Prometheus, to monitor keycloak
# See configuration .yml 
  prometheus:
    image: "quay.io/prometheus/prometheus:v2.37.6"
    ports:
     - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
     - keycloak

