version: "3.9"
services:

# Postgres database
  postgres:
    image: "postgres:16.1-bookworm"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_pw
      - POSTGRES_DB=keycloak

# Keycloak
  keycloak:
    image: "quay.io/keycloak/keycloak:23.0.0"
    ports:
      - "8080:8080"
    environment:
      # db
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=keycloak_pw

      # obs
      - KC_METRICS_ENABLED=true

      # admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

    command: ["start-dev", "--import-realm"]

    volumes:
      - ./realms:/opt/keycloak/data/import

    depends_on:
      - postgres
  
# Prometheus, to monitor keycloak
# See configuration .yml 
  prometheus:
    image: "quay.io/prometheus/prometheus:v2.37.6"
    ports:
     - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
     - keycloak

  grafana:
    image: "grafana/grafana-enterprise"
    ports:
     - "3000:3000"
    volumes:
     - grafana-volume:/var/lib/grafana
    depends_on:
     - prometheus

volumes:
  grafana-volume: {}
